version: '3.8'

services:
  postgres-analytics:
    image: postgres:15
    container_name: ritech_postgres
    restart: on-failure
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/sql-migrations/V1_initial_schema.sql:/docker-entrypoint-initdb.d/01_V1_initial_schema.sql
      - ./database/sql-migrations/V2_create_partitions.sql:/docker-entrypoint-initdb.d/02_V2_create_partitions.sql
      - ./database/sql-migrations/V3_seed_sensor_types.sql:/docker-entrypoint-initdb.d/03_V3_seed_sensor_types.sql
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-raw-ingestion:
    image: mongo:6.0
    container_name: ritech_mongo
    restart: on-failure
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5

  mosquitto-broker:
    image: eclipse-mosquitto
    container_name: ritech_mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - backend

  mqtt-subscriber:
    build: .
    container_name: telemetry-subscriber
    restart: on-failure
    command: ["python", "-u", "app/mqtt_subscriber.py"]
    depends_on:
      mongo-raw-ingestion:
        condition: service_healthy
      mosquitto-broker:
        condition: service_started
      postgres-analytics:
        condition: service_healthy
    env_file:
      - .env
    environment:
      PYTHONPATH: /app
      MQTT_BROKER: mosquitto-broker
      POSTGRES_HOST: postgres-analytics
    networks:
      - backend
  
  publisher:
    build:
      context: ./publisher
    container_name: ritech_publisher
    restart: on-failure
    depends_on:
     - mosquitto-broker
    environment:
      MQTT_BROKER: mosquitto-broker
    networks:
    - backend

volumes:
  pgdata:
  mongodata:

networks:
  backend:
